CREATE TABLE IF NOT EXISTS enterprise_base_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    enterprise_full_name VARCHAR(255) NULL,
    enterprise_short_name VARCHAR(255) NULL,
    enterprise_address VARCHAR(512) NULL,
    enterprise_contact VARCHAR(512) NULL,
    main_products VARCHAR(512) NULL,
    target_customers VARCHAR(512) NULL,
    enterprise_website VARCHAR(512) NULL,
    founded_time VARCHAR(128) NULL,
    industry VARCHAR(255) NULL,
    industry_position VARCHAR(255) NULL,
    sales_region VARCHAR(512) NULL,
    sales_channel VARCHAR(512) NULL,
    service_response_time VARCHAR(128) NULL,
    delivery_time VARCHAR(128) NULL,
    repurchase_rate VARCHAR(128) NULL,
    positive_rate VARCHAR(128) NULL,
    total_revenue VARCHAR(128) NULL,
    employee_count VARCHAR(128) NULL,
    site_area VARCHAR(128) NULL,
    enterprise_advantage VARCHAR(512) NULL,
    product_advantage VARCHAR(512) NULL,
    tech_advantage VARCHAR(512) NULL,
    management_advantage VARCHAR(512) NULL,
    vision VARCHAR(255) NULL,
    purpose VARCHAR(255) NULL,
    mission VARCHAR(255) NULL,
    product_service_advantages LONGTEXT NULL,
    certificates_honors LONGTEXT NULL,
    key_clients LONGTEXT NULL,
    payload_json LONGTEXT NULL,
    development_history LONGTEXT NULL,
    honors LONGTEXT NULL,
    major_events LONGTEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
