CREATE TABLE IF NOT EXISTS article_links (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    enterprise_id BIGINT NULL,
    url VARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

